locale: 'pt'

backend:
  name: git-gateway
  branch: main

display_url: https://zinetrip.site
logo_url: https://zinetrip.site/static/smile.gif

media_folder: static/assets
public_folder: /assets

collections:
  - name: component
    label: Component
    folder: _data/component
    slug: '{{day}}-{{month}}-{{year}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - { name: date, label: Data, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { name: title, label: Título, widget: string }
      - { name: img, label: Imagem, widget: image, required: false }
      - { name: body, label: Body, widget: markdown, required: false }
