locale: 'pt'

backend:
  name: git-gateway
  branch: main

display_url: https://zinetrip.site
logo_url: https://zinetrip.site/static/Trip---paginas.png

media_folder: static/assets
public_folder: /assets

collections:
  - name: component
    label: Component
    folder: _data/component
    slug: '{{day}}-{{month}}-{{year}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - { name: date, label: Data, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { name: title, label: Título, widget: string, required: false }
      - { name: x, label: Posição X, widget: number, required: false }
      - { name: y, label: Posição Y, widget: number, required: false }
      - { name: img, label: Imagem, widget: image, required: false }

  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - file: '_data/component/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
